# Generated by Django 5.1.7 on 2025-03-16 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contribution",
            old_name="request",
            new_name="animation_request",
        ),
    ]
