# Generated by Django 5.1.7 on 2025-03-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visions", "0002_rename_request_contribution_animation_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="animationrequest",
            name="attachments",
            field=models.FileField(
                blank=True, null=True, upload_to="animation_requests/"
            ),
        ),
        migrations.AddField(
            model_name="animationrequest",
            name="budget",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="animationrequest",
            name="views",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="animationrequest",
            name="visibility",
            field=models.BooleanField(default=True),
        ),
    ]
