# Generated by Django 5.1.7 on 2025-03-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "visions",
            "0003_animationrequest_attachments_animationrequest_budget_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="animationrequest",
            name="payment_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
