# Generated by Django 5.1.7 on 2025-04-05 13:21

import django.core.serializers.json
import django.db.models.deletion
import visions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visions", "0004_animationrequest_payment_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenSourceVisionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("2D", "2D Animation"),
                            ("3D", "3D Animation"),
                            ("Motion Graphics", "Motion Graphics"),
                            ("Stop Motion", "Stop Motion"),
                            ("Mixed Media", "Mixed Media"),
                            ("Educational", "Educational"),
                            ("Explainer", "Explainer Video"),
                            ("Short Film", "Short Film"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Beginner Friendly", "Beginner Friendly"),
                            ("Intermediate", "Intermediate"),
                            ("Advanced", "Advanced"),
                            ("Expert", "Expert"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("funding_goal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "current_funding",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "collaboration_link",
                    models.URLField(blank=True, max_length=300, null=True),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                ("visibility", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="os_vision_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Open Source Vision Request",
                "verbose_name_plural": "Open Source Vision Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OpenSourceAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=visions.models.get_opensource_attachment_path
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="visions.opensourcevisionrequest",
                    ),
                ),
            ],
        ),
    ]
