# Generated by Django 5.1.7 on 2025-04-06 00:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visions", "0007_opensourcevisionrequest_collaborators_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeChangeProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("proposed_html_content", models.TextField()),
                ("proposed_css_content", models.TextField()),
                ("proposed_js_content", models.TextField()),
                ("based_on_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Describe the changes made."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved & Merged"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_proposals",
                        to="visions.opensourcevisionrequest",
                    ),
                ),
                (
                    "proposer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_proposals_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_staff": False},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="code_proposals_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Code Change Proposal",
                "verbose_name_plural": "Code Change Proposals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CollaborativeCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "main_html_content",
                    models.TextField(
                        blank=True,
                        default="<html>\n<head>\n</head>\n<body>\n  <h1>Welcome</h1>\n</body>\n</html>",
                    ),
                ),
                (
                    "main_css_content",
                    models.TextField(blank=True, default="/* Approved CSS styles */"),
                ),
                (
                    "main_js_content",
                    models.TextField(blank=True, default="// Approved JavaScript code"),
                ),
                (
                    "last_approved_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="last_approved_code_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborative_code",
                        to="visions.opensourcevisionrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Main Collaborative Code",
                "verbose_name_plural": "Main Collaborative Codes",
            },
        ),
    ]
