# Generated by Django 5.1.7 on 2025-03-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(default=1, upload_to="profile_pics/"),
            preserve_default=False,
        ),
    ]
