# Generated by Django 5.1.7 on 2025-03-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0002_alter_customuser_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("Student", "Student"),
                    ("Teacher", "Teacher"),
                    ("Developer", "Developer"),
                    ("Animator", "Animator"),
                    ("Researcher", "Researcher"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
