# Generated by Django 5.1.7 on 2025-03-19 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0004_customusersocielmedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="following", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
